# Generated by Django 6.0 on 2025-12-10 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_name", models.CharField(max_length=200, unique=True)),
                ("account_id", models.CharField(blank=True, max_length=100, null=True)),
                ("campaign_id", models.CharField(max_length=200)),
                ("tracking_url", models.URLField()),
                ("param_key", models.CharField(blank=True, max_length=200, null=True)),
                ("ttl_seconds", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RunLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("final_url", models.TextField(blank=True, null=True)),
                ("extracted_value", models.TextField(blank=True, null=True)),
                ("raw_response", models.TextField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.mapping"
                    ),
                ),
            ],
        ),
    ]
