# Generated by Django 6.0 on 2025-12-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapping",
            name="manager_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
