# Generated by Django 5.2.9 on 2026-01-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_mapping_ad_group_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("api_key", models.CharField(max_length=64, unique=True)),
                ("api_secret", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="mapping",
            name="account_id",
        ),
        migrations.RemoveField(
            model_name="mapping",
            name="ad_group_id",
        ),
        migrations.RemoveField(
            model_name="mapping",
            name="campaign_id",
        ),
        migrations.RemoveField(
            model_name="mapping",
            name="manager_id",
        ),
        migrations.RemoveField(
            model_name="mapping",
            name="param_key",
        ),
        migrations.RemoveField(
            model_name="mapping",
            name="ttl_seconds",
        ),
        migrations.RemoveField(
            model_name="runlog",
            name="raw_response",
        ),
        migrations.AddField(
            model_name="mapping",
            name="campaign_ids",
            field=models.TextField(
                default="", help_text="Comma separated Google Ads campaign IDs"
            ),
        ),
        migrations.AddField(
            model_name="mapping",
            name="last_suffix",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mapping",
            name="params",
            field=models.JSONField(default=list),
        ),
    ]
