# Generated by Django 5.2.9 on 2026-01-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_scriptauth_remove_mapping_account_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapping",
            name="extract_all_params",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, extract ALL query params from final redirect URL",
            ),
        ),
        migrations.AlterField(
            model_name="mapping",
            name="params",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
