# Generated by Django 5.2.9 on 2026-01-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_mapping_extract_all_params_alter_mapping_params"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mapping",
            name="campaign_ids",
        ),
        migrations.AlterField(
            model_name="mapping",
            name="config_name",
            field=models.CharField(
                help_text="Must exactly match Google Ads campaign name",
                max_length=200,
                unique=True,
            ),
        ),
    ]
