# Generated by Django 5.2.6 on 2026-01-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_mapping_campaign_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapping",
            name="frequency",
            field=models.PositiveIntegerField(
                default=1, help_text="Max number of updates allowed inside the window"
            ),
        ),
        migrations.AddField(
            model_name="mapping",
            name="last_run_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mapping",
            name="window_ms",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total window duration in milliseconds (e.g. 300000)",
            ),
        ),
    ]
